---
# This playbook deploys a db server, a file server, and a web app server
# It also adds monitors to all servers

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  roles:
    - common 

