- name: restart ntp
  service: name=ntpd state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: restart munin-node
  service: name=munin-node state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

