- name: Enable the epel-release repository
  yum: name=epel-release state=present

- name: Install minin-node
  yum: name=munin-node state=present

- name: Add cidr_allow to munin.conf file
  lineinfile: dest=/etc/munin/munin-node.conf line="allow ^192\.168\.77\.[1-9]{2,3}$"

- name: Move service definition to firewalld etc
  copy: dest=/etc/firewalld/services/ owner=root mode=0440 src=munin-node.xml
  notify: restart firewalld
  
- name: Force firewalld restart
  meta: flush_handlers

- name: Add munin-node exception to internal firewall zone
  firewalld: zone=internal service=munin-node permanent=true state=enabled 
  notify: restart firewalld

- name: Start the munin-node service
  service: name=munin-node state=started enabled=true 
